name: "Build a package"

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  packageName: com.riperbool.assetpanel

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
          
      - name: Get Version and Package Name
        id: package-info
        run: |
          version=$(jq -r '.version' package.json)
          name=$(jq -r '.name' package.json)
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "name=$name" >> $GITHUB_OUTPUT
      
      - name: Define file names
        id: file-names
        run: |
          echo "zip-file=${{ steps.package-info.outputs.name }}-${{ steps.package-info.outputs.version }}.zip" >> $GITHUB_OUTPUT
          echo "unity-package=${{ steps.package-info.outputs.name }}-${{ steps.package-info.outputs.version }}.unitypackage" >> $GITHUB_OUTPUT
      
      - name: Create Package Zip
        run: |
          zip -r ${{ steps.file-names.outputs.zip-file }} . \
            -x '*.git*' \
            -x '*.github*' \
            -x '*node_modules*' \
            -x '*.DS_Store'
      
      # Build a list of .meta files for future use
      - name: Track Package Meta Files
        run: |
          find . -name \*.meta \
            ! -path "*/.git/*" \
            ! -path "*/.github/*" \
            ! -path "*/node_modules/*" \
            >> metaList
      
      # Make a UnityPackage version of the Package for release
      - name: Create UnityPackage
        uses: pCYSl5EDgo/create-unitypackage@v1.2.3
        with:
          package-path: ${{ steps.file-names.outputs.unity-package }}
          include-files: metaList
      
      - name: Make Release
        run: |
          gh release create ${{ steps.package-info.outputs.version }} \
              ${{ steps.file-names.outputs.zip-file }} \
              ${{ steps.file-names.outputs.unity-package }} \
              package.json \
              --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
